// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLiXCdU4kF_46u_3Ss9EuXC8NAXTpzARc',
    appId: '1:795193994168:android:75e5abbc87456027eebd4d',
    messagingSenderId: '795193994168',
    projectId: 'nearbylocation-10c7d',
    storageBucket: 'nearbylocation-10c7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7m6yQObJSGI1Q2ksdFF7E1wYCoopr-tk',
    appId: '1:795193994168:ios:d3807aee6ab603daeebd4d',
    messagingSenderId: '795193994168',
    projectId: 'nearbylocation-10c7d',
    storageBucket: 'nearbylocation-10c7d.firebasestorage.app',
    iosBundleId: 'com.example.nearbyride',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7m6yQObJSGI1Q2ksdFF7E1wYCoopr-tk',
    appId: '1:795193994168:ios:d3807aee6ab603daeebd4d',
    messagingSenderId: '795193994168',
    projectId: 'nearbylocation-10c7d',
    storageBucket: 'nearbylocation-10c7d.firebasestorage.app',
    iosBundleId: 'com.example.nearbyride',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBenpQ_4lUp4aqBfDClUlFZjfpM5kya7Jk',
    appId: '1:795193994168:web:d3155f77b8774da8eebd4d',
    messagingSenderId: '795193994168',
    projectId: 'nearbylocation-10c7d',
    authDomain: 'nearbylocation-10c7d.firebaseapp.com',
    storageBucket: 'nearbylocation-10c7d.firebasestorage.app',
    measurementId: 'G-SJZV9J4MJQ',
  );
}
